# Generated by Django 3.2.16 on 2025-03-20 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='widget',
            name='widget_id',
        ),
        migrations.AlterField(
            model_name='widget',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='widget',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='widget',
            name='source_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
