# Generated by Django 3.2.16 on 2025-03-20 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20250320_0918'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userwidget',
            old_name='user',
            new_name='user_profile',
        ),
    ]
